routes/web.php
<?php

use App\Http\Controllers\UsersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/', 'DiscussionsController');

Route::resource('/home', 'DiscussionsController');

Auth::routes(['verify' => true]);

Auth::routes();

Route::resource('discussions', 'DiscussionsController');

Route::resource('discussions/{discussion}/replies', 'RepliesController');

Route::get('users/notifications', [UsersController::class, 'notifications'])->name('users.notifications');
Route::post('discussions/{discussion}/replies/{reply}/mark-as-best-reply', 'DiscussionsController@reply')->name('discussions.best-reply');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\VerifyEmail;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function discussions(){
        return $this->hasMany(Discussion::class);
    }

    public function replies(){
        return $this->hasMany(Reply::class);
    }

    public function sendEmailVerificationNotification()
    {
        $this->notify(new VerifyEmail());
    }

    function isAdmin(){
        return $this->role_id == 2;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function notifications(){
        auth()->user()->unreadNotifications->markAsRead();
        return view('users.notifications', [
            'notifications' => auth()->user()->notifications()->paginate(5)
        ]);
    }
}

resources/views/users/notifications.blade.php
@extends('layouts.app')

@section('content')

<div class="card">
    <div class="card-body">

        <form action="{{ route('discussions.store') }}" method="post" enctype="multipart/form-data" class="container" style="margin-top:5%;">
            <div class="post-body pull-left container" style="border:1px solid #DFDFDF;">
                <div class="card">
                    <div class="card-header">Notificaciones</div>

                    <div class="card-body">

                        @foreach($notifications as $notification)
                        <li class="list-group-item">
                            @if($notification->type === 'App\Notifications\NewReplyAdded')
                            Alguien te ha respondido a

                            <strong>{{ $notification->data['discussion']['title'] }}</strong>
                            <a href="{{ route('discussions.show', $notification->data['discussion']['slug']) }}" class="btn btn-sm btn-info float-right" style="color: white;">
                                Ver discusion
                            </a>
                            @endif
                            @if($notification->type === 'App\Notifications\ReplyMarkedAsBestReply')
                            Tu respuesta a <strong>{{ $notification->data['discussion']['title'] }}</strong> se ha marcado como mejor respuesta
                            <a href="{{ route('discussions.show', $notification->data['discussion']['slug']) }}" class="btn btn-sm btn-info float-right" style="color: white;">
                                Ver discusion
                            </a>
                            @endif
                        </li>
                        @endforeach


                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="container" style="text-align: right;">
        {{$notifications->links("pagination::bootstrap-4")}}
    </div>
</div>

@endsection